### ISSUE TITLE
Sample configuration file missing "accessory": "", field

### ISSUE THREAD

**Issue by prestonmerkel21** [MatthewPattell/homebridge-co2-level#1]
Accessory cannot load after installation without Accessory field (and name field) in Homebridge. See example configuration below of other home bridge accessories or platforms:

},
  "accessories": [
    {
      "accessory": "WeMo",
      "name": "Coffee Maker"
    }
  ],

  "platforms": [
    {
      "platform" : "PhilipsHue",
      "name" : "Hue"
    }

**Comment by MatthewPattell** [comment]
@prestonmerkel21 yes, I fix README.md. Thanks.

**Comment by prestonmerkel21** [comment]
Oh no I’m sorry I meant each accessory needs to have an accessory property. Otherwise homebridge generates an error that it is unable to find the accessory plugin to link to.

**Comment by MatthewPattell** [comment]
@prestonmerkel21 you right, I fixed it)

**Comment by prestonmerkel21** [comment]
Thanks! Last question (sorry to bother you). What is the format the plugin reads from the sensor? I set my http site up to show only a number, but the ppm is always 0, then I did Json {"co2RawValue":"100"} but still reports as 0. How should the value on the webserver be displayed so the plugin may read it?

**Comment by MatthewPattell** [comment]
@prestonmerkel21 if you backend response like this:
```json
{"co2RawValue":"100"}
```

you need set `valuePath`:
```json
"valuePath": "co2RawValue"
```

and check plugin log: `Obtained CO2 value: ?????`
