### ISSUE TITLE
Reading from a local file

### ISSUE THREAD

**Issue by TondaRuzicka** [MatthewPattell/homebridge-co2-level#2]
Hi,

I have a local sensor on my raspberry pi, so I have the data locally. Any tips how to use your plugin (thanks btw) to load this data from the raspberry instead of from an online site? 

I also have the data in firebase realtime database but that seems like an overkill to me. 

Thanks

**Comment by MatthewPattell** [comment]
Hi,

If you haven't access to your sensor through http, you would create simple nodejs application (express).
